### ISSUE TITLE
Error when trying to run 

### ISSUE THREAD

**Issue by gragland** [jbilcke/web4#6]
After installing dependencies and trying to run I'm getting the following error:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/interface/rust.rs:762:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Any idea what it might be?

**Comment by jbilcke** [comment]
Hello @gragland ,

This is a tough one as I never saw this error, and I am not a Rust expert *.

- Was it during `yarn tauri:dev` or `yarn build`?
- which version of `rustc --version` do you have?
- is that on macOS or another system?

As a solution and workaround, I suggest you try to run the app in pure web mode:

```bash
yarn dev
```

And open it in a conventional browser. We can keep this issue open until someone finds a proposer solution to this

_* I'm using Tauri for performance reasons (Tauri generates lightweight ~8 Mb app builds) as an alternative to Electron, but actually I am not a Rust expert myself, I only wrote what's in /src (TypeScript) and not /src-tauri (Rust)_

**Comment by jbilcke** [comment]
I have updated the README to explain the 3 alternatives:
https://github.com/jbilcke/web4#running-the-app

**Comment by gragland** [comment]
Turns out it was because I don't have Rust installed on my M1.. Using `yarn dev` did the trick though! Thanks for the help and awesome project.

**Comment by jbilcke** [comment]
@gragland  don't forget to check the latest version (I've just pushed to `main`)

 is it much better (tabs, better progression follow-up etc) 🙂 

https://twitter.com/flngr/status/1608814377813299200

note: it used Yarn 3.3 so you may have a bit of setup to do (if you try to just re-run `yarn` I think it should work)

**Comment by gragland** [comment]
Thanks, new version is working great 🙌
